### ISSUE TITLE
Local assets do not take environment variables into account

### ISSUE THREAD

**Issue by sjadema** [johndwells/craft.minimee#11]
The configuration for non-standard $filesystemPath and $baseUrl (e.g. not [DOCUMENT_ROOT] does not take Craft's environmentVariables into account. If you set $baseUrl = {siteUrl} & $filesystemPath = {basePath} (both of those variables are defined in my craft/config/general.php for multi-environment purposes) setAssets() in MinimeeService will not parse those environment variables.

I will create a pull request to fix this.

**Comment by johndwells** [comment]
Hi,

Actually Minimee should be parsing environment variables already.  What version were you working with? Could you raise a ticket with a detailed explanation of how you're configuring Minimee, and I can try to help resolve this?

Cheers,
John

**Comment by sjadema** [comment]
You're right, they should get parsed by getFilesystemPath in Minimee_SettingsModel. Strange... I'm using 0.9.3 with the following settings;

![craft_settings](https://cloud.githubusercontent.com/assets/5380502/6117180/325731c8-b0b3-11e4-937c-f43fb030e5e9.PNG)

general.php;
![image](https://cloud.githubusercontent.com/assets/5380502/6117224/52d17792-b0b3-11e4-899a-ab43e2a4ee81.png)

**Comment by sjadema** [comment]
Strange, i'm fiddling with some logging and it seems to work out of the box :s Before i posted this issue i did some extensive research (logging, clearing cache, etc.). The values in the database are the same aswell. Either my server made a boo-boo or i'm slowly going insane. Anyways, you can close this issue and decline the pull request as i can't even reproduce the issue myself.

**Comment by johndwells** [comment]
Glad you were able to get it working!

It's worth mentioning that you should be able to leave Filesystem Path & Base URL blank in your case.  Left blank, Minimee will ask Craft what these values should be - and Craft will parse environmentVariables at that point.
