### ISSUE TITLE
Getting query parameters after asset URL

### ISSUE THREAD

**Issue by KnutSv** [johndwells/craft.minimee#13]
Here's an example of an URL i get:
fe8a00a77747efb025acf43971fee8e0942bb788.css?d=1425477542

Why does minimee add what looks like a timestamp after the filename?

1. If the name itself is a hash of the contents, why need an additional cachebust?
2. If the parameter is a timestamp (last changed presumably) this is not good, you don't want to bust cache unless the newly saved file is actually different
3. According to this article using query parameters to cache-bust is bad practise: http://stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring

**Comment by johndwells** [comment]
Hi,

The query string is the method used to cachebust when you're using Craft's own storage folder to cache asset combining/minifying. But if you set Minimee up to use a cache folder that you've explicitly created, e.g. /public/cache, then Minimee will write the filenames to include the timestamp, and forego the query string method.

Cheers,
John

**Comment by KnutSv** [comment]
Great, thanks for the quick reply :)

**Comment by johndwells** [comment]
Sure thing - thanks for giving Minimee a go!
