### ISSUE TITLE
Image cache-busting.

### ISSUE THREAD

**Issue by krazyjakee** [johndwells/craft.minimee#15]
I'm looking for a solution to change the filename of images in the css whenever the images are changed. Is that possible now? If no, is it something worthy of the roadmap?

**Comment by johndwells** [comment]
Hi Jake,

That's a bit beyond the scope of Minimee's realm of responsibility, so you'll have to work on a different solution...

There is "Bust" (https://straightupcraft.com/craft-plugins/bust) which can add a timestamp to the end of a filename.  To use it though you'd have to move at least some of your CSS into your templates to run it.

Cheers,
John

**Comment by krazyjakee** [comment]
Very kind response.

Thank you.
