### ISSUE TITLE
Issue with calc() in CSS

### ISSUE THREAD

**Issue by KnutSv** [johndwells/craft.minimee#17]
If I have Minimee active, spaces inside CSS calc() get removed. Example:

```css
padding-right: calc(24px + 2.25em);
```
becomes:

```css
padding-right: calc(24px+2.25em);
```

which is invalid.
I've checked the code before it's passed to Minimee and it is fine. Also if i toggle Minimee off, the CSS calc spaces are not removed.

**Comment by johndwells** [comment]
Hi Knut,

This looks to be a bug with the underlying minification library (https://code.google.com/p/minify/).  Until there's a fix, it sounds like a hacky workaround would be to subtract a negative number, e.g.:

`padding-right: calc(24px - -2.25em);`

Not ideal, but at least it won't hold you up!

**Comment by johndwells** [comment]
I'm currently testing a new css minification library which resolves this bug. I'm hoping that in the coming weeks I'll be able to cut a release and get this finally resolved!

**Comment by johndwells** [comment]
Hi Knut,

I'm happy to say that as of v0.9.7 this has now been resolved - the underlying library Minify was updated to 2.3, which includes this fix.

Cheers,
John
