### ISSUE TITLE
can't make it works

### ISSUE THREAD

**Issue by benoitvb** [johndwells/craft.minimee#24]
I've enabled the plugin and put my assets into public/assets/js and public/assets/js folders.
Then I referenced the files in my template but it looks that the plugin isn't minified nor combine anything.
I'm working locally with MAMP. I didn't change anything on the settings panel though.

What have I missed?

**Comment by johndwells** [comment]
Hi @benoitvb,

If you turn on `devMode` (https://craftcms.com/docs/config-settings#devMode), then Minimee will throw errors as to what might be wrong.  Most likely, you are referencing a file that couldn't be found.

If devMode doesn't reveal the problem, can you paste in an example of how you're using Minimee in your template?

Cheers,
John
