### ISSUE TITLE
Getting this error on some some hosted Craft sites

### ISSUE THREAD

**Issue by E2design** [johndwells/craft.minimee#27]
I'm getting this error on some (but not all) hosted Craft sites where Minimee 0.9.8 is installed. Any glues?

Warning: Declaration of Craft\Minimee_SettingsModel::getAttribute($name) should be compatible with Craft\BaseModel::getAttribute($name, $flattenValue = false) in /storage/av04135/www/craft/plugins/minimee/models/Minimee_SettingsModel.php on line 17

**Comment by johndwells** [comment]
That's odd - Minimee_SettingsModel's getAttribute() method does have that signature.  Can you tell me what's on line 260 of `minimee/models/Minimee_SettingsModel.php`?

**Comment by E2design** [comment]
Hi John,

There isn't much on line 260 just a {

I've attached the whole file you.


Rob

**Comment by E2design** [comment]
Hi John,

Any progress on finding/solving this issue?

Rob

**Comment by janson** [comment]
I experience this same issue. Digging in, v.0.9.8 does not include the commit which solves the error. 

@E2design I nabbed the master package, which side-stepped the problem for me.

**Comment by johndwells** [comment]
@E2design @janson I've finally cut an official release which includes the fix for this bug: https://github.com/johndwells/craft.minimee/releases/tag/v0.9.9
