### ISSUE TITLE
Error with PHP 7.1 - [PHP notice] "A non well formed numeric value encountered"

### ISSUE THREAD

**Issue by oles** [johndwells/craft.minimee#28]
Works when downgraded to 7.0.9, and fails when upgraded to 7.1.1

Created an issue for it at https://github.com/mrclay/minify/issues/566 👍 

craftcms/plugins/minimee/library/vendor/mrclay/minify/min/lib/CSSmin.php(769)

757 return ($slice === FALSE) ? '' : $slice;
758 }
759
760 /**
761 * Convert strings like "64M" or "30" to int values
762 * @param mixed $size
763 * @return int
764 */
765 private function normalize_int($size)
766 {
767 if (is_string($size)) {
768 switch (substr($size, -1)) {
769 case 'M': case 'm': return $size * 1048576;
770 case 'K': case 'k': return $size * 1024;
771 case 'G': case 'g': return $size * 1073741824;
772 }
773 }
774
775 return (int) $size;
776 }
777 }

**Comment by green-plastic** [comment]
This plugin just needs to have the updated version of mrclay/minify which is 3.x.

**Comment by brianrivet** [comment]
I'm having this issue as well. Is there an update on when this might be fixed or is there a procedure to fix it myself?

**Comment by johndwells** [comment]
@brianrivet @green-plastic @oles Can you guys try the latest version on the `develop` branch and see if it resolves this 7.1x compat issue?

**Comment by brianrivet** [comment]
Hi John,

I just loaded it onto my php 7.1 test site and it fixed the issue and appears to working fine.

Thanks!

Brian Rivet
brian@odysseydesignstudio.com
Phone: 225-505-9243
Fax: 225-300-8517
www.odysseydesignstudio.com

**Comment by johndwells** [comment]
Great, thanks for testing, sorry all for the slow turnaround on this fix.

Fixed in release 0.9.9: https://github.com/johndwells/craft.minimee/tree/v0.9.9

**Comment by green-plastic** [comment]
Thanks! Worked great.
