### ISSUE TITLE
Craft 3 support

### ISSUE THREAD

**Issue by skramstad** [johndwells/craft.minimee#39]
Hi.

Will there be support for Craft 3?

Thanks!

**Comment by johndwells** [comment]
You're the first person to ask! :)

Yes, I do plan on porting Minimee to C3, though it likely will not happen until closer to C3's April 2018 release.  If you'd be willing to help test any beta versions, I'd be much obliged.

**Comment by skramstad** [comment]
That is awesome news 🥇 

And ofcourse, I will gladly test any beta versions. Just give me a heads up :)

**Comment by ryanmasuga** [comment]
John, we would test a beta version when you're ready.

**Comment by green17** [comment]
John, we would be happy to test a beta version too. Great plugin we used in Craft 2.

**Comment by marksimons** [comment]
+1

**Comment by ryanmasuga** [comment]
We ended up sort of writing a lightweight Minimee-style utility thing. Would still consider using Minimee, as there are years of coding experience behind it. Or we may beef up our utility...whichever comes first as time marches on!

**Comment by simonkuran** [comment]
Any update on this? Minimee was my go-to solution for Craft 2. I'd love to continue to use it for Craft 3.

**Comment by bitboxfw** [comment]
We have developed a new plugin for Craft 3 - https://github.com/bitboxde/minifier

**Comment by vandres** [comment]
@bitboxfw booh! 19$ :D
