### ISSUE TITLE
Feature: Minimizing inline javascript

### ISSUE THREAD

**Issue by brettdewoody** [johndwells/craft.minimee#7]
This might already be possible, but if so I'm not doing it correctly.

Is it possible to wrap inline javascript and have `{filter minimee}` minimize it?

**Comment by johndwells** [comment]
Hey @brettdewoody I know this has been open for ages, but there is now a new plugin that can give you inline minification:

https://github.com/khalwat/minify

Therefore I'm going to close out this ticket. :)
