### ISSUE TITLE
HTML minification?

### ISSUE THREAD

**Issue by leeaston** [johndwells/craft.minimee#9]
Hi John,

any plans to add this?

Best wishes
Lee

**Comment by Jammooka** [comment]
For what it's worth, you can wrap the entire layout file with {% spaceless %}[page]{% endspaceless %}

Obviously doesn't do the same job as actual minification, but worth knowing.

**Comment by johndwells** [comment]
Hey both,

You may be interested to know that there is now a plugin available which exclusively is built to minify inline content (HTML, CSS & JS):

https://github.com/khalwat/minify

Cheers,
John
